services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./sqlite_db:/data # Mount the shared volume at /data in the web container
    environment:
      TURNSTILE_SECRET: ${TURNSTILE_SECRET}
      DB_PATH: /data/guest_book.db
      NODE_ENV: production
    restart: unless-stopped

volumes:
  sqlite_db:
