services:
  web:
    image: ghcr.io/domza64/domzas-webspace:main
    ports:
      - "3000:3000"
    volumes:
      - ./PATH_TO_DATA_FOLDER:/app/data # Must be writable by the container (UID=65532)
    environment:
      TURNSTILE_SECRET: ${TURNSTILE_SECRET}
    restart: unless-stopped
