services:
  web:
    image: ghcr.io/Domza64/Domzas-Webspace:latest
    ports:
      - "3000:3000"
    volumes:
      - ./sqlite_db:/app/data
    environment:
      TURNSTILE_SECRET: ${TURNSTILE_SECRET}
    restart: unless-stopped

volumes:
  sqlite_db:
